### PR TITLE
Save excerpts of the news entries if the user wants it

### PR DESCRIPTION
**Pull request by gehaxelt**
This should implement the requested excerpt feature from #44

### CODE REVIEW

**Comment by gehaxelt** [comment]
I haven't had time to thoroughly test this feature yet. Any feedback/bugs are welcome!

**Comment by Hotspeed** [comment]
Please add Support for IPv6
Please add delay 2 or 3 second for showing rss update on irc, sometimes bot have Excess Flood

**Comment by gehaxelt** [comment]
@Hotspeed please create a separate issue and merge request :-)

**Comment by gehaxelt** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
