### PR TITLE
Add url colour control and tweak !last / !lastfeed

### PR DESCRIPTION
**Pull request by leifmadsen**
Add the 'self.url' configuration option to control the colour output
of the URLs. By default it was using red which was difficult to read
in some terminals.

Tweak the !last and !lastfeed commands to both return consistently
(previously order was inverted from each other). Also adjust the loop
to return from newest to oldest.

### CODE REVIEW

**Comment by gehaxelt** [comment]
Hi @leifmadsen , 
thanks for the PR. 

> Also adjust the loop
> to return from newest to oldest.

I used oldest -> newest, so that the most recent news would show up at the bottom and  one would not need to scroll. 
Maybe we can add an option for that as well?

**Comment by leifmadsen** [comment]
Ah that makes sense... I guess it seemed more natural to me to have the newest at the top, but I see the point of having it the other way.

Really all we would need would be a boolean to control that, and then append the `[::-1]` back to the output (or alternatively, pass the boolean to control the SQL `SELECT` statement.. which might actually be cleaner and more obvious).

If we're going to be modifying the class to allow passing in options from `config.py` then it probably makes more sense to just adjust the `SELECT` statement since it's the cleaner option.

**Comment by leifmadsen** [comment]
Maybe what I should do for now is put the `[::-1]` code back in for this PR to keep the list mostly the same (the change to the `SELECT` statement would stay to at least get both `!last` and `!lastfeed` returning in the same order).

Then we can add in the adjustments in another PR.

**Comment by gehaxelt** [comment]
Passing the config to the DB and using an option for changing the ordering is a good idea and we should put that into a new PR. 

~~So maybe you could add the `[::-1]` code and remove the `order by` in the query so that both `!last` and `!lastfeed` have the same order?~~

Nvm: I noticed that the ordering in the SQL query is missing, so keep it in there and we'll fix the ordering with `[::-1]` in another PR.

**Comment by gehaxelt** [comment]
@leifmadsen May you please merge the current master into your PR to resolve the merge conflicht? I think I'll merge your PR afterwards.

**Comment by gehaxelt** [comment]
Hey @leifmadsen 

I've implemented your changes and ideas in https://github.com/gehaxelt/python-rss2irc/pull/41. 

I thought it might be easier to copy your changes instead of fiddling around with a MR :) So I'll close this one if you're happy with the other one.

**Comment by leifmadsen** [comment]
@gehaxelt that's fine with me! Sorry for lack of response. I've been crazy with work lately, and this was really a side project that I haven't fully implemented :)

**Comment by gehaxelt** [comment]
Hey, 
no worries! 

Have some nice last days of 2016 ;)

**Pull request closed without merging**
